### ISSUE TITLE
Weird error only occurs when I get to the main screen in Tarkov.

### ISSUE THREAD

**Issue by SargeantsTechTipsYT** [CJ-SPT/PerformanceImprovements#10]
![2024-12-16 23_00_43-Xbox](https://github.com/user-attachments/assets/7c7abf1e-d2e8-42e3-b7e0-f0aad95484d6)

I only seem to get this error when fully launched into Tarkov, I am going to remove it for the time being. Hopefully this helps!

**Comment by CJ-SPT** [comment]
Read the mod page. You're missing a dependency. This is not an issue.

**Comment by SargeantsTechTipsYT** [comment]
I see that now, I do apologize for wasting your time, you even put it in big text for dumb people like me. Sorry!

Not sure how I didn't see that, but thank you for responding so quick! :)

**Comment by SargeantsTechTipsYT** [comment]
Good to close!
