### ISSUE TITLE
[Fika] Bots are sooo dumd

### ISSUE THREAD

**Issue by TheDronBit** [CJ-SPT/PerformanceImprovements#11]
Hi, when using this modification with SAIN and FIKA, bots become insanely dumb, stare at walls, shoot randomly, and weird things happen. The result is the same on older and newer versions of these mods. During testing, I completely wiped all configs and mod files and installed everything from scratch.

**Comment by TheDronBit** [comment]
It would be insanely good if this modification did not affect bots at all, then there would be no problems (I think so).

**Comment by CJ-SPT** [comment]
> It would be insanely good if this modification did not affect bots at all, then there would be no problems (I think so).

Where do you think any performance gain here comes from? Bot modification. Closing as this is a duplicate issue anyway.
