### ISSUE TITLE
bots freezed on all maps

### ISSUE THREAD

**Issue by krisis111** [CJ-SPT/PerformanceImprovements#12]
i am using fika and sain and although 0.22 greatly improved performance it also broke the bots hahaha

**Comment by TheInfamousAlk** [comment]
Same here. I have not found a fix. However, dev stated they will not provide support to fika users, so I guess we're SOL

**Comment by CJ-SPT** [comment]
Yeah I'm sorry but Fika has been the bane of my existence for a long time now and I don't care to look into specific issues it has with stuff that I develop. Closing this.

**Comment by TheInfamousAlk** [comment]
Yeah I don't blame you. Maybe you can add a toggle to completely disable all bot-related functions in the settings? At least that would let us make it work without figuring out exactly why it doesn't. (It may also be useful for non-fika users who have other mods that modify AI in ways that conflict)

**Comment by krisis111** [comment]
0.2.1 works fine so there is no problem. 
thanks for the reply
