### ISSUE TITLE
Sanitar is frozen

### ISSUE THREAD

**Issue by Agoelia** [CJ-SPT/PerformanceImprovements#6]
[LogOutput.log](https://github.com/user-attachments/files/18141258/LogOutput.log)
[FullLogOutput.log](https://github.com/user-attachments/files/18141260/FullLogOutput.log)
![1](https://github.com/user-attachments/assets/af284e49-a8c2-4536-8491-2f1cb3025100)
![2](https://github.com/user-attachments/assets/6bb36408-2330-450c-8a67-b9543f54b148)

Sanitar was standing in place, I presume at his spawn point.
His guards spawned correctly, fought and died as normal. Other bots also spawned and behaved normally.

Other bosses in other raids did not have this issue,

I am playing on the latest version of SPT AKI, all my mods are updated. My MOAR configs are the defaults.

I had already posted the issue on SAIN's Github, and I was told "It might be caused by Performance Improvements latest update."

**Comment by CJ-SPT** [comment]
I'll look into it, thanks

**Comment by MuRongMoQing** [comment]
> I'll look into it, thanks

As a supplement, in my game, Santa Claus encountered the above-mentioned issue (yes, I modified the time of the relevant holiday). On the other hand, The Goons generate and participate in battles normally. In the Chinese community where I am located, someone found that Kaban in his archive also had this situation, and his bodyguards did indeed stick to their posts and attack correctly.

**Comment by CJ-SPT** [comment]
Resolved in commit: https://github.com/CJ-SPT/PerformanceImprovements/commit/fba3e194d05172dcbdf1112f505395c42f3de4fc

**Comment by Agoelia** [comment]
Are you sure that commit will fix this? I don't play with FIKA

**Comment by CJ-SPT** [comment]
Closing as duplicate issue.
